# Generated by Django 5.2.3 on 2025-07-10 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadoras', '0002_remove_calculadoradivisa_activa'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_origen', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto origen')),
                ('moneda_origen', models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('EUR', 'Euro'), ('ARS', 'Peso Argentino'), ('BOB', 'Boliviano'), ('BRL', 'Real Brasileño'), ('CLP', 'Peso Chileno'), ('MXN', 'Peso Mexicano'), ('PEN', 'Sol Peruano'), ('UYU', 'Peso Uruguayo'), ('PYG', 'Guaraní Paraguayo')], max_length=3, verbose_name='Moneda origen')),
                ('monto_destino', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto destino')),
                ('moneda_destino', models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('EUR', 'Euro'), ('ARS', 'Peso Argentino'), ('BOB', 'Boliviano'), ('BRL', 'Real Brasileño'), ('CLP', 'Peso Chileno'), ('MXN', 'Peso Mexicano'), ('PEN', 'Sol Peruano'), ('UYU', 'Peso Uruguayo'), ('PYG', 'Guaraní Paraguayo')], max_length=3, verbose_name='Moneda destino')),
                ('relacion_conversion', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Relación de conversión')),
                ('direccion', models.CharField(choices=[('directa', 'Directa'), ('inversa', 'Inversa')], max_length=10, verbose_name='Dirección de conversión')),
                ('fecha_conversion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de conversión')),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del usuario')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('calculadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones', to='calculadoras.calculadoradivisa', verbose_name='Calculadora')),
            ],
            options={
                'verbose_name': 'Historial de Conversión',
                'verbose_name_plural': 'Historial de Conversiones',
                'ordering': ['-fecha_conversion'],
            },
        ),
    ]
