# Generated by Django 5.2.3 on 2025-07-07 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_presupuesto_monto_restante_gasto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('ARS', 'Peso Argentino'), ('BOB', 'Boliviano'), ('EUR', 'Euro')], default='ARS', max_length=3),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('ARS', 'Peso Argentino'), ('BOB', 'Boliviano'), ('EUR', 'Euro')], default='ARS', max_length=3),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='presupuestos.categoria'),
        ),
    ]
