# Generated by Django 5.2.3 on 2025-07-07 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0005_gasto_adjunto_delete_archivoadjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='gastos_adjuntos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
