# Generated by Django 5.2.3 on 2025-07-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_remove_gasto_adjunto_archivoadjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='gastos_adjuntos/'),
        ),
        migrations.DeleteModel(
            name='ArchivoAdjunto',
        ),
    ]
