# Generated by Django 5.2.3 on 2025-07-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0008_remove_gasto_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
