# Generated by Django 5.2.3 on 2025-07-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculadoraDivisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo para esta relación de conversión', max_length=100)),
                ('moneda_origen', models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('EUR', 'Euro'), ('ARS', 'Peso Argentino'), ('BOB', 'Boliviano'), ('BRL', 'Real Brasileño'), ('CLP', 'Peso Chileno'), ('MXN', 'Peso Mexicano'), ('PEN', 'Sol Peruano'), ('UYU', 'Peso Uruguayo'), ('PYG', 'Guaraní Paraguayo')], max_length=3)),
                ('moneda_destino', models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('EUR', 'Euro'), ('ARS', 'Peso Argentino'), ('BOB', 'Boliviano'), ('BRL', 'Real Brasileño'), ('CLP', 'Peso Chileno'), ('MXN', 'Peso Mexicano'), ('PEN', 'Sol Peruano'), ('UYU', 'Peso Uruguayo'), ('PYG', 'Guaraní Paraguayo')], max_length=3)),
                ('relacion', models.DecimalField(decimal_places=10, help_text='Relación de conversión (1 moneda_origen = X moneda_destino)', max_digits=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Calculadora de Divisa',
                'verbose_name_plural': 'Calculadoras de Divisas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
