# Generated by Django 5.2.3 on 2025-07-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadoras', '0003_historialconversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialconversion',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario'),
        ),
    ]
